### ISSUE TITLE
Comment to keywords in FITS headers

### ISSUE THREAD

**Issue by alvaroribas** [cespaillat/EDGE#13]
It is possible to add comments to the keywords in the headers of FITS files, for example:

![screen shot 2018-01-18 at 3 53 33 pm](https://user-images.githubusercontent.com/2198885/35120958-c6c8d228-fc67-11e7-88ba-06849e622c19.png)

It would be great to have them in the collated FITS files for the disk parameters to avoid confusion, and it would also be helpful to have the units just in case.

**Comment by emaciasq** [comment]
The last commit should solve this.
