### ISSUE TITLE
Moving non-DIAD functions from EDGE.py to util.py

### ISSUE THREAD

**Issue by emaciasq** [cespaillat/EDGE#2]
Candidate functions I have initially identified:

Functions (or sets of functions) that are not used in the rest of EDGE, and do not use any other EDGE function or class:
- [x] deci_to_time
- [x] time_to_deci
- [x] calcAngularDist
- [x] convertFreq (I am not sure we need to keep this one)
- [x] diskMassCalc
- [x] apparent_to_absolute
- [x] convertMagErr
- [x] star_param (uses convertSptype)
- [x] convertSptype
- [x] MdotCalc (uses convertMag)
- [x] convertMag (uses convertJy)
- [x] convertJy

Functions that do not use any other EDGE functions or classes, but are used in some other EDGE functions, so they could be moved to util.py in the future and be imported from there:
- [x] ~~filelist (could be substituted by glob?)~~
- [x] linearInterp
- [ ] normalize

**Comment by connorrobinson** [comment]
Filelist has now been removed and replaced with glob.

**Comment by connorrobinson** [comment]
All of the functions above have been moved into util with the exception of normalize. This one heavily relied on the structure of the TTS_Obs class (and thus would not be useful as a standalone function in util).
